#!/usr/bin/env python

import os
import sys
from twisted.web import server, resource, static
from twisted.logger import textFileLogObserver, globalLogPublisher
from twisted.internet import reactor, endpoints

globalLogPublisher.addObserver(textFileLogObserver(sys.stdout))
static.File.childNotFound = static.File("./error/404.html")
port = int(os.getenv("PORT", 5000))
root = static.File("./public")
site = server.Site(root)
endpoint = endpoints.TCP4ServerEndpoint(reactor, port)
endpoint.listen(site)
reactor.run()
